### ISSUE TITLE
Bug with apertures?

### ISSUE THREAD

**Issue by keflavich** [cmcclellan1010/dendrocat#3]
I'm trying to use a fixed circular aperture:

```
fixed_circle = Circle([0, 0], 20*u.arcsec, name='fixedcirc')
matched.photometer(fixed_circle)
```

and I encounter this traceback:

```
  File "/Users/adam/work/alma-imf/cataloging/catalog_7m_images.py", line 54, in <module>
    matched.photometer(fixed_circle)
  File "/Users/adam/repos/dendrocat/dendrocat/mastercatalog.py", line 152, in photometer
    peak_data[j] = np.max(pix_in_aperture[j])
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2334, in amax
    initial=initial)
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

> /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/numpy/core/fromnumeric.py(83)_wrapreduction()
     81                 return reduction(axis=axis, out=out, **passkwargs)
     82
---> 83     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     84
     85
```

**Comment by keflavich** [comment]
The aperture appears to extract no pixels, but the catalog should only include regions within the image.  Even if it didn't, though, it's a common use case to match catalogs between images of different sizes, so the aperture extraction should be robust against the case where an aperture is empty.

**Comment by cmcclellan1010** [comment]
Exceptions have been added for apertures that extract no pixels. Now, the photometry data should return `nan` instead of crashing. This has been tested for empty numpy arrays, but please update the thread if this doesn't patch your issue correctly.

To determine why the aperture isn't extracting the right pixels in the first place, try making a catalog with just the troublesome sources and try to get photometry data on them using a few different apertures (fixed, variable, different radii, etc.). Does it happen across the board, or is it just the fixed apertures?

**Comment by keflavich** [comment]
Is it a problem with setting the aperture x_cen/y_cen?

**Comment by cmcclellan1010** [comment]
Was this resolved by your previous pull request? If so, I'll go ahead and close the issue.
